### ISSUE TITLE
MMPs coda

### ISSUE THREAD

**Issue by lilychen0126** [MarkusFerdinandDablander/QSAR-activity-cliff-experiments#1]
Hello, I'm very interested in your work and I think your idea of combining activity cliffs with QSAR is great! However, I was a bit confused about MMPs generation when reading the paper and the code. Would you be able to provide the code for generating MMPs?

**Comment by MarkusFerdinandDablander** [comment]
Hi Lilychen,

Thank you for your interest in our work! It is much appreciated.

We generate MMPs using the publicly available mmpdb Python package which you can find here: https://github.com/rdkit/mmpdb

We look for MMPs that respect the following commonly used size constraints: The MMP core was required to contain at least twice as many heavy atoms as either of the two variable parts; each variable part was required to contain no more than $13$ heavy atoms; the maximal size difference between both variable parts was set to eight heavy atoms; and bond cutting was restricted to single exocyclic bonds.

MMPs using these size constraints can be constructed via the mmpdb package by running the following code snippet from the command line:

mmpdb fragment X_smiles.csv --cut-smarts 'exocyclic' --delimiter comma -o X_smiles.fragments;mmpdb index X_smiles.fragments --max-variable-heavies 13 --max-heavies-transf 8 --max-variable-ratio 0.3333333 --out 'csv' -o X_smiles_mmps.csv

Here X_smiles.csv is a .csv file that contains two columns: one column with SMILES strings and another column that assigns an integer identifier to each SMILES string (screenshot attached).
![Screenshot from 2023-03-20 13-35-04](https://user-images.githubusercontent.com/25180655/226340538-09a1a442-282f-4994-994a-5329901a1fab.png)

Hope this helps!

**Comment by lilychen0126** [comment]
Thank you very much for your reply! Your assistance has been extremely valuable to me and has allowed me to successfully generate MMPs. I would like to express my sincerest gratitude and thanks to you！

**Comment by MachineGUN001** [comment]
> --cut-smarts 'exocyclic'

@MarkusFerdinandDablander , many thanks to provide such an interesting method to do AC analysis.
when I try to run the command line you mentioned, the error occured as below

`mmpdb fragment: error: Error in command-line option '--cut-smarts' ("'exocyclic'"): unable to parse SMARTS`


is 'exocyclic' the wrong SMART format? Is there an alternative SMART code for fragments generation as a limitation?
many thanks,

Sh-Y
